object-calisthenics:

  # Rule #1: One level of indentation per method.
  CalisthenicsIndentRule:
    active: true

  # Rule #2: Don’t use the ELSE keyword.
  CalisthenicsNoElseRule:
    active: true

  # Rule #3: Wrap all primitives and Strings.
  CalisthenicsWrapPrimitivesRule:
    active: true

  # Rule #4: First class collections.
  CalisthenicsWrapCollectionsRule:
    active: true

  # Rule #5: One dot per line.
  CalisthenicsDotsRule:
    active: true
    
  # Rule #6: Don’t abbreviate.
  CalisthenicsNoAbbreviationsRule:
    active: true

  # Rule #7: Keep all entities small.
  CalisthenicsSmallRule:
    active: true
    ignoreAnnotated:
      - 'org.junit.Test'
      - 'org.junit.jupiter.api.Test'
      - 'org.junit.jupiter.api.TestFactory'
      - 'org.junit.jupiter.api.RepeatedTest'
      - 'org.junit.jupiter.params.ParameterizedTest'
      - 'org.junit.jupiter.api.Nested'
      - 'org.junit.jupiter.api.extension.ExtendWith'

  # Rule #8: No classes with more than two instance variables.
  CalisthenicsInstanceVarRule:
    active: true

  # Rule #9: No getters/setters/properties.
  CalisthenicsNoExposeRule:
    active: true
  
  # Rule #10: All classes must have state.
  CalisthenicsStateRule:
    active: true
